version: '3'
services:
  web:
    build: .
    ports:
     - "4000:4000"
    volumes:
      - .:/app
    environment:
      - PORT=4000
      - NODE_ENV=development
      - GITHUB_API_URL=https://api.github.com

